@startuml Dawlet Sequence
actor User
database fs
participant Cubase
participant Launcher
participant Algolet
participant Sheetlet
participant Rolelet
database PkgRegistry
database Github

== Initialization ==

User -> Launcher: Click Launcher App
Launcher -> Launcher: Start the core server
Launcher -> PkgRegistry: Fetch installable Dawlets
Launcher <-- PkgRegistry: Installable Dawlets
Launcher -> fs: Scan Installed Dawlets
fs --> Launcher: Installed Dawlets' Paths
User <- Launcher: Show Installed/Installable Dawlets
alt Install
  User -> Launcher: Click on the Install Dawlet button
  Launcher -> Github: Fetch the latest Dawlet
  Launcher <-- Github: $(DawletName).app
  fs <- Launcher: Save the downloaded Dawlet
end
alt Uninstall
  User -> Launcher: Click on the Uninstall Dawlet button
  fs <- Launcher: Remove the Dawlet from Application folder
end
alt Launch
  User -> Launcher: Click on the launch button
  Launcher -> Algolet: Launch Algolet(example)
end


== Import ==

alt Optional
  Cubase -> Launcher: DnD(?)/export MIDI
  Launcher -> Launcher: parse MIDI
  Launcher -> Launcher: createGroup(s)
  Launcher --> Algolet: broadcast group
  Launcher --> Sheetlet: broadcast group
  Launcher --> Rolelet: broadcast group
end

== Export ==

autonumber
User -> Launcher: Open Export Options
User -> Launcher: Configure which groups to export
alt Export as File
  User -> Launcher: Click Export button
  User <- Launcher: Prompt dialog
  User --> Launcher: configure export path
  fs <-- Launcher: Save SMF
else Direct Export
  autonumber 3
  Cubase <-- Launcher: DnD SMF
end

@enduml