@startuml
actor User
database fs


== Initialization ==

User -> Launcher: Click Launcher App
Launcher -> Launcher: Start the core server
Launcher -> PkgRegistry: Fetch available Dawlets
Launcher <-- PkgRegistry: Available Dawlets
Launcher -> fs: Scan Installed Dawlets
fs --> Launcher: Installed Dawlets' Paths
User <- Launcher: Show Installed/Installable Dawlets
User -> Launcher: Click on the Install Dawlet button
Launcher -> Github: Fetch the latest Dawlet
Launcher <-- Github: $(DawletName).app
fs <- Launcher: Save the downloaded Dawlet
User -> Launcher: Click on the launch button
Launcher -> Algolet: Launch Algolet(example)

@enduml