name: Node CI(yogo)

on:
  push:
    branches:
      - yogo

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: change directory
      run: cd yogo && pwd
    - name: install
      run: yarn
    - name: build
      run: yarn build
    - name: test
      run: yarn test
